version: '3.9'

services:

  # SQL SERVER DATABASE
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: shopez-sqlserver

    restart: always

    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    networks:
      - shopez-network


  # OCELOT API GATEWAY
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile

    container_name: shopez-apigateway

    restart: always

    ports:
      - "5000:8080"

    depends_on:
      - authservice
      - productservice
      - orderservice

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

    networks:
      - shopez-network


  # AUTH SERVICE
  authservice:
    build:
      context: ./Services/AuthService
      dockerfile: Dockerfile

    container_name: shopez-authservice

    restart: always

    ports:
      - "5001:8080"

    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=AuthDB;
        User Id=sa;
        Password=YourStrong@Pass123;
        TrustServerCertificate=True;

    networks:
      - shopez-network


  # PRODUCT SERVICE
  productservice:
    build:
      context: ./Services/ProductService
      dockerfile: Dockerfile

    container_name: shopez-productservice

    restart: always

    ports:
      - "5002:8080"

    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=ProductDB;
        User Id=sa;
        Password=YourStrong@Pass123;
        TrustServerCertificate=True;

    networks:
      - shopez-network


  # ORDER SERVICE
  orderservice:
    build:
      context: ./Services/OrderService
      dockerfile: Dockerfile

    container_name: shopez-orderservice

    restart: always

    ports:
      - "5003:8080"

    depends_on:
      - sqlserver

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=OrderDB;
        User Id=sa;
        Password=YourStrong@Pass123;
        TrustServerCertificate=True;

    networks:
      - shopez-network


  # ANGULAR FRONTEND
  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile

    container_name: shopez-frontend

    restart: always

    ports:
      - "4200:80"

    depends_on:
      - apigateway

    networks:
      - shopez-network


# NETWORKS
networks:
  shopez-network:
    driver: bridge


# VOLUMES
volumes:
  sqlserver_data: